import { Project } from "./types";

export const projectsData: Project[] = [
  {
    id: 7,
    title: "Verdict",
    slug: "verdict-run",
    seoTitle: "Verdict.run Competitive Programming Platform | yust.dev",
    description: "The Ultimate Competitive Programming Platform.",
    fullDescription:
      "Solve Codeforces problems with a built-in IDE, Whiteboard, and Custom Judge—no more tab switching. Features Mirror Mode, Smart IDE, and Algorithm Visualization.",
    tag: "Competitive Programming",
    icon: "fa-gavel",
    span: "md:col-span-3 md:row-span-1", // Full width headliner
    delay: "delay-100",
    video: "/videos/verdict.webm",
    poster: "/static/images/posters/verdict.webp",
    repoLink: "https://github.com/YUST777/verdict-community",
    siteLink: "https://verdict.run",
    technologies: ["Next.js 15", "TypeScript", "Puppeteer", "Monaco Editor", "Excalidraw"],
    drawerId: "verdict",
    features: [
      {
        category: "Core",
        svgIcon: "code",
        items: ["Mirror Mode", "Smart IDE", "Whiteboard Integration"],
      },
      {
        category: "Architecture",
        svgIcon: "server",
        items: ["Browser Extension", "Scraper Service", "Dockerized"],
      },
    ],
  },
  {
    id: 8,
    title: "Sast",
    slug: "sast-tech",
    seoTitle: "Sast.tech Autonomous AI Security Agent Project | yust.dev",
    description: "Autonomous AI Security Agent.",
    fullDescription:
      "An AI autonomous agent that fetches your web app, finds vulnerabilities, patches the code, and generates a verified report. Sast automates the full security lifecycle—identifying, fixing, and verifying vulnerabilities with functional POCs. It ensures your software is secured as fast as it is coded, delivering superior precision through total process optimization.",
    tag: "AI Security",
    icon: "fa-robot",
    span: "md:col-span-3 md:row-span-1",
    delay: "delay-150",
    video: "/videos/sast.webm",
    poster: "/static/images/posters/sast.webp",
    technologies: ["AI / LLMs", "Node.js", "Cybersecurity", "Autonomous Agents", "Docker"],
    siteLink: "https://sast.tech",
    drawerId: "sast",
    features: [
      {
        category: "Automated Lifecycle",
        svgIcon: "bolt",
        items: ["Auto-Discovery", "Auto-Patching", "POC Generation"],
      },
      {
        category: "Integration",
        svgIcon: "globe",
        items: ["Web App Fetching", "Visual Reporting", "Fast Verification"],
      },
    ],
  },
  {
    id: 2,
    title: "Gifts Charts",
    slug: "gifts-charts",
    seoTitle: "Gifts Charts Telegram Analytics Bot Project | yust.dev",
    description: "Real-time Telegram sticker & gift price tracking bot.",
    fullDescription:
      "A sophisticated Telegram bot for tracking live sticker prices and gift collections, featuring real-time data fetching, premium subscription systems, and automated image generation.",
    tag: "Automation",
    icon: "fa-robot",
    span: "md:col-span-1 md:row-span-1",
    delay: "delay-100",
    video: "/videos/giftscharts.webm",
    poster: "/static/images/posters/giftscharts.webp",
    technologies: ["Python", "Telegram API", "Docker", "PostgreSQL", "Flask"],
    drawerId: "giftsCharts",
    features: [
      {
        category: "Core Features",
        svgIcon: "chart",
        items: ["Live Price Tracking", "Premium Subscriptions", "Admin Dashboard", "Auto-Updates"],
      },
      {
        category: "Architecture",
        svgIcon: "server",
        items: ["Microservices", "Docker Containerized", "Async Database", "CDN Service"],
      },
    ],
  },
  {
    id: 13,
    title: "10K Runner",
    slug: "10k-runner",
    seoTitle: "10K Runner Web3 Infinite Runner Game Project | yust.dev",
    description: "Infinite runner game that makes you EARN & fun.",
    fullDescription:
      "A fast-paced 3D infinite runner game built in 3 days for the 10k Squad international contest. Play, collect coins, and earn rewards while running through procedurally generated Web3 worlds.",
    tag: "Web3 Game",
    icon: "fa-gamepad",
    span: "md:col-span-2 md:row-span-1",
    delay: "delay-150",
    video: "/videos/10krunner.webm",
    poster: "/static/images/posters/10krunner.webp",
    siteLink: "https://10krunner.fun",
    technologies: ["React", "Three.js", "React Three Fiber", "Web3", "Tailwind CSS"],
    drawerId: "runner10k",
    features: [
      {
        category: "Core Features",
        svgIcon: "bolt",
        items: ["Infinite Running", "3D Browser Environment", "Coin Collection"],
      },
      {
        category: "Contest Metrics",
        svgIcon: "trophy",
        items: ["3rd Place Winner", "Built in 3 Days", "International Stage"],
      },
    ],
  },
  {
    id: 14,
    title: "SWRMZ",
    slug: "swrmz",
    seoTitle: "SWRMZ Cooperative Swarm AI Security Project | yust.dev",
    description: "Cooperative Swarm AI Security agents.",
    fullDescription:
      "A swarm of AI security agents built on Band.ai for the Lablab.ai hackathon. SWRMZ hunts vulnerabilities across your stack, remediates them automatically, and monitors runtime logs.",
    tag: "AI Security",
    icon: "fa-robot",
    span: "md:col-span-2 md:row-span-1",
    delay: "delay-200",
    video: "/videos/swrmz.webm",
    poster: "/static/images/posters/swrmz.webp",
    siteLink: "https://swrmz.tech",
    technologies: ["Band.ai", "AI Agents", "Next.js", "Cybersecurity"],
    drawerId: "swrmz",
  },
  {
    id: 9,
    title: "Collectable Kit",
    slug: "collectable-kit",
    seoTitle: "Collectable Kit Telegram Mini App Project | yust.dev",
    description: "Next-gen collectibles management platform.",
    fullDescription:
      "A comprehensive platform designed for modern collectors. Track, value, and manage your digital and physical collections with real-time analytics and a sleek, high-performance interface.",
    tag: "Social",
    icon: "fa-box-open",
    span: "md:col-span-1 md:row-span-1",
    delay: "delay-250",
    video: "/videos/collectablekit.webm",
    poster: "/static/images/posters/collectablekit.webp",
    technologies: ["Next.js", "PostgreSQL", "Tailwind CSS", "Lucide Icons"],
    drawerId: "collectablekit",
  },
  {
    id: 4,
    title: "ICPCHUE",
    slug: "icpc-hue",
    seoTitle: "ICPC HUE Competitive Programming Platform | yust.dev",
    description: "Hardened, sandboxed online judge platform.",
    fullDescription:
      "I led the development of the ICPC HUE training platform, a comprehensive training ecosystem serving the community. Built with Next.js, featuring secure registration, gamified dashboards, and skill trackers.",
    tag: "Platform",
    icon: "fa-code",
    span: "md:col-span-3 md:row-span-1",
    delay: "delay-300",
    video: "/videos/icpchue2.webm",
    poster: "/static/images/posters/icpchue2.webp",
    drawerId: "ICPCHUE",
  },
  {
    id: 1,
    title: "Zero Threat",
    slug: "zero-threat",
    seoTitle: "Zero Threat AI Cybersecurity Platform Project | yust.dev",
    description: "National award-winning AI-driven security ecosystem.",
    fullDescription:
      "A comprehensive AI-powered cybersecurity suite comprising a web platform, browser extension, and Windows agent, designed for advanced threat intelligence and real-time protection.",
    tag: "Cybersecurity",
    icon: "fa-shield-alt",
    span: "md:col-span-3 md:row-span-1",
    delay: "delay-350",
    video: "/videos/zerothreat.webm",
    poster: "/static/images/posters/zerothreat.webp",
    drawerId: "zerothreat",
  },
  {
    id: 15,
    title: "Sketchz",
    slug: "sketchz",
    seoTitle: "Sketchz Ethereum 3D Web3 Art Game Project | yust.dev",
    description: "A 3D game where you draw on ETH.",
    fullDescription:
      "Sketchz — a 3D game where you draw on ETH. Mint blank, draw it, sell it. Step into a 3D museum on Ethereum: draw your own pieces, watch others create in real-time, and buy or sell art right off the wall.",
    tag: "Web3 Game",
    icon: "fa-paint-brush",
    span: "md:col-span-2 md:row-span-1",
    delay: "delay-250",
    video: "/videos/bunny.webm",
    poster: "/static/images/posters/bunny.webp",
    technologies: ["Three.js", "WebGL", "Solidity", "Next.js", "Ethereum"],
    drawerId: "sketchz",
  },
  {
    id: 5,
    title: "More Projects",
    description: "Additional projects and experiments",
    fullDescription:
      "Explore additional projects, experiments, and creative work showcasing various technologies and solutions.",
    icon: "fa-archive",
    span: "md:col-span-1 md:row-span-1",
    delay: "delay-200",
    isMinimal: true,
    isArchive: true,
    video: "/videos/moreprojects.webm",
    poster: "/static/images/posters/moreprojects.webp",
    technologies: ["Various Technologies"],
  },
  {
    id: 6,
    title: "yousefdev",
    description: "Building practical solutions",
    fullDescription:
      "A developer focused on building practical tools and applications. Creating clean, well-architected solutions with a focus on user experience and impact.",
    tag: "",
    span: "md:col-span-3 md:row-span-1",
    delay: "delay-300",
    isLarge: true,
    video: "/videos/yousefdev.webm",
    poster: "/static/images/posters/yousefdev.webp",
    drawerId: "yousefdev",
    technologies: ["Full-Stack Development", "Cybersecurity", "Automation"],
    features: [
      {
        category: "Services",
        svgIcon: "code",
        items: ["Web development", "Application development", "System design"],
      },
      {
        category: "Expertise",
        svgIcon: "lightbulb",
        items: ["Full-stack development", "Web applications", "Automation systems"],
      },
    ],
  },
];

export const archiveProjectsData: Project[] = [
  {
    id: 10,
    title: "PanoBlue",
    slug: "panoblue",
    seoTitle: "PanoBlue Corporate Import Export Website | yust.dev",
    description: "Import/Export Corporate Platform",
    fullDescription:
      "A custom-built digital presence for an international import/export company, migrating from WordPress to a tailored, high-performance web solution.",
    tag: "Corporate",
    icon: "fa-globe",
    span: "md:col-span-1 md:row-span-1",
    delay: "delay-100",
    video: "/videos/panoblue.webm",
    poster: "/static/images/posters/panoblue.webp",
    drawerId: "panoblue",
  },
  {
    id: 11,
    title: "Fazzah",
    slug: "fazzah",
    seoTitle: "Fazzah Full-Stack Web Application Project | yust.dev",
    description: "Efficient Web Application Solution",
    fullDescription:
      "A streamlined web application designed for efficiency and performance, focusing on a clean user interface and robust backend integration.",
    tag: "Web App",
    icon: "fa-rocket",
    span: "md:col-span-1 md:row-span-1",
    delay: "delay-200",
    video: "/videos/fazzah.webm",
    poster: "/static/images/posters/fazzah.webp",
    drawerId: "fazzah",
  },
  {
    id: 12,
    title: "RetroOS",
    slug: "retro-os",
    seoTitle: "RetroOS Browser Operating System Project | yust.dev",
    description: "Interactive Retro OS Simulation",
    fullDescription:
      "A nostalgic browser-based operating system simulation with an interactive terminal, desktop windows, and retro interface experiments.",
    tag: "Experimental",
    icon: "fa-terminal",
    span: "md:col-span-1 md:row-span-1",
    delay: "delay-300",
    video: "/videos/RetroOS_Project.webm",
    poster: "/static/images/posters/RetroOS_Project.webp",
    drawerId: "RetroOS",
  },
];
