/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokenUsageRouteImport } from './routes/token-usage'
import { Route as MainRouteImport } from './routes/_main'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainProjectsRouteImport } from './routes/_main/projects'
import { Route as MainHacksRouteImport } from './routes/_main/hacks'
import { Route as MainBlogIndexRouteImport } from './routes/_main/blog.index'
import { Route as MainBlogPostIdRouteImport } from './routes/_main/blog.$postId'

const TokenUsageRoute = TokenUsageRouteImport.update({
  id: '/token-usage',
  path: '/token-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainProjectsRoute = MainProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => MainRoute,
} as any)
const MainHacksRoute = MainHacksRouteImport.update({
  id: '/hacks',
  path: '/hacks',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogIndexRoute = MainBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => MainRoute,
} as any)
const MainBlogPostIdRoute = MainBlogPostIdRouteImport.update({
  id: '/blog/$postId',
  path: '/blog/$postId',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/token-usage': typeof TokenUsageRoute
  '/hacks': typeof MainHacksRoute
  '/projects': typeof MainProjectsRoute
  '/blog/$postId': typeof MainBlogPostIdRoute
  '/blog/': typeof MainBlogIndexRoute
}
export interface FileRoutesByTo {
  '/token-usage': typeof TokenUsageRoute
  '/hacks': typeof MainHacksRoute
  '/projects': typeof MainProjectsRoute
  '/': typeof MainIndexRoute
  '/blog/$postId': typeof MainBlogPostIdRoute
  '/blog': typeof MainBlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/token-usage': typeof TokenUsageRoute
  '/_main/hacks': typeof MainHacksRoute
  '/_main/projects': typeof MainProjectsRoute
  '/_main/': typeof MainIndexRoute
  '/_main/blog/$postId': typeof MainBlogPostIdRoute
  '/_main/blog/': typeof MainBlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/token-usage'
    | '/hacks'
    | '/projects'
    | '/blog/$postId'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to: '/token-usage' | '/hacks' | '/projects' | '/' | '/blog/$postId' | '/blog'
  id:
    | '__root__'
    | '/_main'
    | '/token-usage'
    | '/_main/hacks'
    | '/_main/projects'
    | '/_main/'
    | '/_main/blog/$postId'
    | '/_main/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  TokenUsageRoute: typeof TokenUsageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/token-usage': {
      id: '/token-usage'
      path: '/token-usage'
      fullPath: '/token-usage'
      preLoaderRoute: typeof TokenUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/projects': {
      id: '/_main/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof MainProjectsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/hacks': {
      id: '/_main/hacks'
      path: '/hacks'
      fullPath: '/hacks'
      preLoaderRoute: typeof MainHacksRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/': {
      id: '/_main/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof MainBlogIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/blog/$postId': {
      id: '/_main/blog/$postId'
      path: '/blog/$postId'
      fullPath: '/blog/$postId'
      preLoaderRoute: typeof MainBlogPostIdRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainHacksRoute: typeof MainHacksRoute
  MainProjectsRoute: typeof MainProjectsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBlogPostIdRoute: typeof MainBlogPostIdRoute
  MainBlogIndexRoute: typeof MainBlogIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainHacksRoute: MainHacksRoute,
  MainProjectsRoute: MainProjectsRoute,
  MainIndexRoute: MainIndexRoute,
  MainBlogPostIdRoute: MainBlogPostIdRoute,
  MainBlogIndexRoute: MainBlogIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  TokenUsageRoute: TokenUsageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
